CREATE DATABASE IF NOT EXISTS pandan_kitchen;
USE pandan_kitchen;

CREATE TABLE IF NOT EXISTS Feedback (
    Feedback_ID INT AUTO_INCREMENT PRIMARY KEY,
    Feedback_date DATE NOT NULL,
    Name VARCHAR(80) NOT NULL,
    Emailid VARCHAR(120) NOT NULL,
    Phone VARCHAR(15) NOT NULL,
    Feedback VARCHAR(1000) NOT NULL,
    Promotion CHAR(1) NOT NULL DEFAULT 'N',
    Channel_S CHAR(1) NOT NULL DEFAULT 'N',
    Channel_W CHAR(1) NOT NULL DEFAULT 'N',
    Channel_M CHAR(1) NOT NULL DEFAULT 'N'
);
